# Generated by Django 5.2.1 on 2025-06-03 15:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreuploads', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersubmission',
            options={'verbose_name': 'مشاركة المستخدم', 'verbose_name_plural': 'مشاركات المستخدمين'},
        ),
        migrations.AlterField(
            model_name='usersubmission',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة'),
        ),
        migrations.AlterField(
            model_name='usersubmission',
            name='description',
            field=models.TextField(verbose_name='الوصف'),
        ),
        migrations.AlterField(
            model_name='usersubmission',
            name='image',
            field=models.ImageField(upload_to='uploads/', verbose_name='الصورة'),
        ),
        migrations.AlterField(
            model_name='usersubmission',
            name='title',
            field=models.CharField(max_length=100, verbose_name='العنوان'),
        ),
        migrations.AlterField(
            model_name='usersubmission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
    ]
