# Generated by Django 5.2.1 on 2025-06-03 16:21

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreuploads', '0002_alter_usersubmission_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubmission',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='الصورة'),
        ),
    ]
